### ISSUE TITLE
integrate frinkiac!

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/MinnBot#17]
https://www.frinkiac.com/

Figure out whether there's an API, whether someone will make a Slack/Hubot integration, etc.

**Comment by jonathanstegall** [comment]
watch https://libraries.io/npm/hubot-frinkiac. Currently at version 0.0.0 because I mean the thing just went public.

**Comment by okize** [comment]
@jonathanstegall there's definitely some refactoring to be done but it's in a working early state now: https://github.com/okize/hubot-frinkiac

**Comment by jonathanstegall** [comment]
@okize brilliant!
